<a href="https://colab.research.google.com/github/YukiRndo/Top-100-Docker-Labs-Linux/blob/main/N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from pandas import DataFrame

cars = {
'make': ['Ford', 'Honda', 'Toyota', 'Tesla'],
'model': ['Taurus', 'Accord', 'Camry', 'Model S'],
'MSRP': [27595, 23570, 23495, 68000]
}

carData = DataFrame(cars)

carData

print('carData.index = ', carData.index)

print('carData.columns = ', carData.columns)

carData2 = DataFrame(cars, index = [1,2,3,4])

carData2['year'] = 2018

carData2['dealership'] = [
'Courtesy Ford',
'Capital Honda',
'Spartan Toyota',
'North Tesla'
]

carData2

carData.index =  RangeIndex(start=0, stop=4, step=1)
carData.columns =  Index(['make', 'model', 'MSRP'], dtype='object')


,make,model,MSRP,year,dealership
1,Ford,Taurus,27595,2018,Courtesy Ford
2,Honda,Accord,23570,2018,Capital Honda
3,Toyota,Camry,23495,2018,Spartan Toyota
4,Tesla,Model S,68000,2018,North Tesla


In [2]:
from pandas import Series
import numpy as np

s2 = Series(np.random.randn(6))

print('Series s2 =\n', s2, '\n')

print('s2.values = ', s2.values)

print('s2.index = ', s2.index)

print('s2.dtype = ', s2.dtype)

Series s2 =
 0    0.653470
1   -0.963127
2   -1.046740
3    0.804277
4    0.956190
5    0.019608
dtype: float64 

s2.values =  [ 0.65347037 -0.96312654 -1.04674034  0.80427656  0.95619024  0.0196084 ]
s2.index =  RangeIndex(start=0, stop=6, step=1)
s2.dtype =  float64


In [3]:
import numpy as np

print('Uniform')
print(np.random.rand(5))

print('\nNormal')
print(np.random.randn(5))

print('\nArange')
print(np.arange(-10,10,2))

print('\nReshape')
print(np.arange(12).reshape(3,4))

print('\nLinspace')
print(np.linspace(0,1,10))

print('\nLogspace')
print(np.logspace(-3,3,7))

print('\nZeros')
print(np.zeros((2,3)))

print('\nOnes')
print(np.ones((3,2)))

print('\nIdentity')
print(np.eye(3))

Uniform
[0.09117715 0.28333687 0.18087909 0.37835551 0.48783847]

Normal
[ 0.01362227 -1.86793551 -1.38744694  0.49822282 -0.93330377]

Arange
[-10  -8  -6  -4  -2   0   2   4   6   8]

Reshape
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Linspace
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Logspace
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]

Zeros
[[0. 0. 0.]
 [0. 0. 0.]]

Ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np

oneDim = np.array([1.0,2,3,4,5])

print(oneDim)

print("#Dimensions =", oneDim.ndim)

print("Dimension =", oneDim.shape)

print("Size =", oneDim.size)

print("Array type =", oneDim.dtype)

[1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64


In [5]:
intlist = [1,3,5,7,9]

print(type(intlist))

print(intlist)

intlist2 = list(range(0,10,2))

print(intlist2)

print(intlist[2])

print(intlist[:2])

print(intlist[2:])

print(len(intlist))

<class 'list'>
[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8]
5
[1, 3]
[5, 7, 9]
5


In [6]:
s1 = "This"

print(s1[1:])

print(len(s1))

print("Length of string is " + str(len(s1)))

print(s1.upper())

print(s1.lower())

his
4
Length of string is 4
THIS
this
